import { chromium } from 'playwright-core';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--no-sandbox'] });
const ctx = await browser.newContext({ viewport: { width: 1280, height: 1000 } });
const page = await ctx.newPage();
const errors = [];
page.on('pageerror', (e) => errors.push('PAGEERROR ' + e.message));
page.on('console', (m) => { if (m.type() === 'error') errors.push('CONSOLE ' + m.text()); });
await page.goto('http://127.0.0.1:5199/#/generic');
await page.waitForTimeout(3000);
const before = await page.locator('body').innerText();
console.log('BEFORE generic snippet:', (before.match(/D\+\d+\.\d/g) || []).slice(0, 4));
await page.goto('http://127.0.0.1:5199/#/polls');
await page.waitForTimeout(1500);
await page.getByRole('button', { name: 'Add a poll' }).click();
await page.fill('#ap', 'Test Pollster');
await page.fill('#ad', '60');
await page.fill('#ar2', '30');
await page.getByRole('button', { name: 'Add poll' }).click();
await page.waitForTimeout(1500);
console.log('has yours chip:', await page.getByText('yours').count());
await page.screenshot({ path: '/tmp/shot-polls-added.png' });
await page.goto('http://127.0.0.1:5199/#/generic');
await page.waitForTimeout(3000);
const after = await page.locator('body').innerText();
console.log('AFTER generic snippet:', (after.match(/D\+\d+\.\d/g) || []).slice(0, 4));
console.log(errors.join('\n') || 'no errors');
await browser.close();
