import { chromium } from 'playwright-core';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--no-sandbox'] });
const ctx = await browser.newContext({ viewport: { width: 400, height: 860 } });
const page = await ctx.newPage();
const errors = [];
page.on('pageerror', (e) => errors.push('PAGEERROR ' + e.message));
page.on('console', (m) => { if (m.type() === 'error') errors.push('CONSOLE ' + m.text()); });
await page.goto('http://127.0.0.1:5199/#/night');
await page.waitForTimeout(2000);
await page.locator('.night-tabs button', { hasText: 'Live map' }).click();
await page.waitForTimeout(1200);
await page.getByRole('button', { name: /Blitz/ }).click();
await page.getByRole('button', { name: /Play/ }).first().click();
await page.waitForTimeout(9000);
await page.evaluate(() => window.scrollTo(0, 700));
await page.waitForTimeout(800);
await page.screenshot({ path: '/tmp/m-live-play.png' });
console.log(errors.join('\n') || 'no errors');
await browser.close();
