import { chromium } from 'playwright-core';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--no-sandbox'] });
const page = await (await browser.newContext({ viewport: { width: 1000, height: 700 } })).newPage();
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
await page.goto('http://127.0.0.1:5199/#/');
await page.waitForTimeout(2500);
await page.keyboard.press('/');
await page.keyboard.type('kaptur');
await page.waitForTimeout(300);
await page.screenshot({ path: '/tmp/palette.png' });
await page.keyboard.press('Enter');
await page.waitForTimeout(1500);
console.log('hash after Enter:', await page.evaluate(() => location.hash));
await page.keyboard.press('Control+k');
await page.keyboard.type('penn');
await page.waitForTimeout(300);
console.log('results:', await page.locator('.pal-list li').allInnerTexts().then((a) => a.map((x) => x.replace(/\s+/g, ' ')).slice(0, 5)));
await page.keyboard.press('Escape');
console.log('closed:', (await page.locator('.pal').count()) === 0, errors.join(';') || 'no errors');
await browser.close();
